//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272Del3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DonationDetails = new HashSet<DonationDetail>();
            this.WithdrawalDetails = new HashSet<WithdrawalDetail>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductInfo { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public int CategoryID { get; set; }
        public float Cost { get; set; }
        public System.DateTime ProductAddDate { get; set; }
        public Nullable<int> GenderID { get; set; }
        public int Size { get; set; }
        public Nullable<System.DateTime> BestBefore { get; set; }
        public int ColorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationDetail> DonationDetails { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual ProductCondition ProductCondition { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawalDetail> WithdrawalDetails { get; set; }
    }
}
